### ISSUE TITLE
Handle for foreign key fields

### ISSUE THREAD

**Issue by phoebebright** [jimjkelly/printen#11]
I've created an index that includes foreign key fields like this::

    @classmethod
     def get_document(cls, obj):
         fields = (
            'modelname',
            'sig_code',
            'sig_access',
            'who.handle',
            'who.first_name',
            'who.last_name',
            'who.user_type',
            'who.email',
            'who.telephone',
            'who.title',
            'who.about',
            'who.notes',
            'who.last_updated',
            'who.is_active',
        )

But this causes problems in javascript because of the . in the field name.   It would be nice to be able to do use __ instead, eg::

    fields = (
            'modelname',
            'sig_code',
            'sig_access',
            'who__handle',
            'who__first_name',
            'who__last_name',

**Comment by jimjkelly** [comment]
You can make the field names anything you want, I don't believe the key names of the returned dictionary map to the model anywhere except for the `get_document` function, so feel free to do `"who__handle": obj.who.handle`.  Let me know if that makes sense?  We can video chat if it doesn't.

**Comment by phoebebright** [comment]
Yes - had a modified version from you docs and it all got over complicated.  Went back to version as described in docs and all is well!
